---
title: ""
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
    css: PranaStyle.css
    self_contained: false
    keep_md: yes
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Introduction
```{r child="subsections/Introduction_to_geoSpectral/Introduction_to_geoSpectral.Rmd"}
```

# Obtaining and Installing
```{r child="subsections/Obtaining_and_Installing/Obtaining_and_Installing.Rmd"}
```

# Provided Classes
```{r child="subsections/geoSpectral_Classes/geoSpectral_Classes.Rmd"}
```

# Importing and Subsetting Data
```{r child="subsections/Importing_Data/Importing_Data.Rmd"}
```

# Accessing Data
```{r child="subsections/Accessing_Data/Accessing_Data.Rmd"}
```

# Plotting
```{r child="subsections/Plotting/Plotting.Rmd"}
```

